sudo: required
services:
  - docker

before_install:
  - docker build -t yhy2008/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run yhy2008/react-test npm test -- --coverage

after_success:
  - docker build -t yhy2008/multi-react ./client
  - docker build -t yhy2008/multi-nginx ./nginx
  - docker build -t yhy2008/multi-server ./server
  - docker build -t yhy2008/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push yhy2008/multi-react
  - docker push yhy2008/multi-nginx
  - docker push yhy2008/multi-server
  - docker push yhy2008/multi-worker